import type { Metadata } from "next";
import { Geist, Geist_Mono, Hind_Siliguri, Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from 'next-themes'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const hindSiliguri = Hind_Siliguri({
  weight: ['400', '600', '700'],
  subsets: ['bengali'],
  variable: '--font-hind',
});
const notoBengali = Noto_Sans_Bengali({
  weight: ['300', '400', '600'],
  subsets: ['bengali'],
  variable: '--font-noto',
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${hindSiliguri.variable} ${notoBengali.variable} h-full antialiased`}
    >
      <body className="min-h-full w-full flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
